version: "3.7"

services:
   backend:
      container_name: admin_api
      build:
        context: .
        dockerfile: Dockerfile
      environment:
          DB_HOST: db
          DB_DATABASE: sergygy
          DB_USERNAME: rootserg
          DB_PASSWORD: Poiu123
      ports:
      - 8000:8000
      volumes:
      - .:/app
      depends_on:
      - db
      networks:
      - app

  db:
     container_name: admin_db
     image: mysql:5.7.22
     environment:
        MYSQL_DATABASE: sergygy
        MYSQL_USER: rootserg
        MYSQL_PASSWORD: Poiu123
        MYSQL_ROOT_PASSWORD: Poiu123
     volumes:
        - .dbdata:/var/lib/mysql
     ports:
        - 33066:3306
     networks:
        - app

networks:
  app:
